  version: '3'

  networks:
    network-1:
      driver: bridge

  services:
    backend:
      build: 
        context: .
        dockerfile: docker/back/Dockerfile
      ports:
        - '3000:3000'
      volumes:
        - ./backend:/app
        - /app/node_modules
      environment:
        - NODE_ENV=development
      restart: unless-stopped

    frontend:
      build:       
        context: .
        dockerfile: docker/front/Dockerfile
      ports:
        - '8080:8080'
      depends_on:
        - backend
      volumes:
        - ./frontend:/app
      restart: always