FROM node:18 as build-stage

WORKDIR /app

COPY ../frontend/package*.json ./
RUN npm install

COPY ../frontend/ .

RUN npm run build



FROM nginx:stable-alpine

COPY --from=build-stage /app/dist /usr/share/nginx/html

COPY ../docker/front/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]